// Code generated from the Community control API route and request schema.
// Re-run the capture-control integration workflow when the local capture API
// changes. Do not edit this file to accept arbitrary paths or fields.
package cloudconnector

const (
	DefaultLocalCaptureStartPath = "/api/v1/captures"
	DefaultLocalCaptureStopPath  = "/api/v1/captures/{captureID}/stop"
)

func localCaptureStartFields() []string {
	return []string{"name", "mode", "segment_size_mib", "segment_seconds", "max_files", "stop_after_seconds", "retention_lock", "start_reason"}
}
